### PR TITLE
fix lodash bug

### LINKED ISSUE #159: Punjabi translation not working
<div> Freshdesk Ticket ID: <a href="https://khalishelp.freshdesk.com/a/tickets/80">80</a></div>
                       <div> Freshdesk Ticket Agent: Aman Singh</div>
                       <div> Freshdesk Ticket Agent Email: helpdesk@khalisfoundation.org</div>
                       <div> Ticket Priority: Medium</div>
                       <div> Freshdesk Ticket Description: </div><table border="0" width="100%" cellspacing="0" cellpadding="0" style="background-color:#f7f9fc">
<tbody>
<tr>
<td></td>
</tr>
<tr>
<td align="center">
<table border="0" width="500" cellspacing="0" cellpadding="0" style="background-color:#eeeeee">
<tbody>
<tr>
<td bgcolor="#EEEEEE" width="4"></td>
<td bgcolor="#EEEEEE" width="30"></td>
<td style="font-size: 16px; vertical-align: middle; color: #f9922b; padding-top:
2px; line-height: 20px" align="left" bgcolor="#EEEEEE"><strong>Feedback
Form</strong></td>
</tr>
</tbody>
</table>
<table border="0" width="500" cellspacing="0" cellpadding="0" style="background-color:#eeeeee">
<tbody>
<tr>
<td bgcolor="#EEEEEE" width="4"></td>
<td align="center" bgcolor="#FFFFFF">
<table id="emailFieldsTable" class="mceNonEditable" border="0" width="100%" cellspacing="0" cellpadding="5">
<tbody>
<tr>
                            <td bgcolor="white" style="padding:5px !important" width="30%">Please select which platform you are using:-</td>
                            <td bgcolor="white" width="70%" style="padding:5px
!important">Desktop Version</td>
                        </tr>
<tr>
                            <td bgcolor="#f9f9f9" style="padding:5px
!important" width="30%">Feedback Type</td>
                            <td bgcolor="#f9f9f9" width="70%" style="padding:5px
!important">Bug Reports</td>
                        </tr>
<tr>
                            <td bgcolor="white" style="padding:5px !important" width="30%">What went wrong?</td>
                            <td bgcolor="white" width="70%" style="padding:5px
!important">Punjabi translation not showing in Ang search</td>
                        </tr>
<tr>
                            <td bgcolor="#f9f9f9" style="padding:5px
!important" width="30%">What should have happened instead?</td>
                            <td bgcolor="#f9f9f9" width="70%" style="padding:5px
!important">Shown punjabi translation before</td>
                        </tr>
<tr>
                            <td bgcolor="white" style="padding:5px !important" width="30%">How can the issue be recreated by our team?</td>
                            <td bgcolor="white" width="70%" style="padding:5px
!important">1.open sikhitothemax.org<br>
2. Search by ang<br>
3. Enter "2"<br>
4. In display option turn on punjabi translation<br>
</td>
                        </tr>
<tr>
                            <td bgcolor="#f9f9f9" style="padding:5px
!important" width="30%">Which web browser are using?</td>
                            <td bgcolor="#f9f9f9" width="70%" style="padding:5px
!important">Chrome</td>
                        </tr>
<tr>
                            <td bgcolor="white" style="padding:5px !important" width="30%">What version is your browser?</td>
                            <td bgcolor="white" width="70%" style="padding:5px
!important">80</td>
                        </tr>
<tr>
                            <td bgcolor="#f9f9f9" style="padding:5px
!important" width="30%">Operating System</td>
                            <td bgcolor="#f9f9f9" width="70%" style="padding:5px
!important">Other</td>
                        </tr>
<tr>
                            <td bgcolor="white" style="padding:5px !important" width="30%">Name</td>
                            <td bgcolor="white" width="70%" style="padding:5px
!important">Prabhdeep Singh</td>
                        </tr>
<tr>
                            <td bgcolor="#f9f9f9" style="padding:5px
!important" width="30%">E-mail</td>
                            <td bgcolor="#f9f9f9" width="70%" style="padding:5px
!important">prabhdeepanesar@gmail.com</td>
                        </tr>
<tr>
                            <td bgcolor="white" style="padding:5px !important" width="30%">Phone Number</td>
                            <td bgcolor="white" width="70%" style="padding:5px
!important">(+91) 9914477760</td>
                        </tr>
<tr>
                            <td bgcolor="#f9f9f9" style="padding:5px
!important" width="30%">email value</td>
                            <td bgcolor="#f9f9f9" width="70%" style="padding:5px
!important">4232dd1abe4757d992e00ba7868fafb64348174627a59ba985ceba947ad2658c</td>
                        </tr>
</tbody>
</table>
</td>
<td bgcolor="#EEEEEE" width="4"></td>
</tr>
<tr>
<td style="font-size: 4px" bgcolor="#EEEEEE"></td>
<td style="font-size: 4px" bgcolor="#EEEEEE"></td>
<td style="font-size: 4px" bgcolor="#EEEEEE"></td>
</tr>
</tbody>
</table>
</td>
</tr>
<tr>
<td></td>
</tr>
<tr>
<td>
<div style="text-align: center; font-size: 11px">You can <a href="https://www.jotform.com/edit/4635631567551131090?utm_source=emailfooter&amp;utm_medium=email&amp;utm_term=80266126732151&amp;utm_content=edit_submissions&amp;utm_campaign=notification_email_footer_submission_links&amp;email_type=notification" style="color: #2160d2" target="_blank" rel="noreferrer">edit this submission</a> and <a href="https://www.jotform.com/submissions/80266126732151?utm_source=emailfooter&amp;utm_medium=email&amp;utm_term=80266126732151&amp;utm_content=view_all_submissions&amp;utm_campaign=notification_email_footer_submission_links" style="color: #2160d2" target="_blank" rel="noreferrer">view all your submissions</a>
easily.</div>
</td>
</tr>
<tr>
<td></td>
</tr>
</tbody>
</table>

### PR DESCRIPTION
**Pull request by ManjotS**
fixes #159

### CODE REVIEW

File: api/lib/getJSON.js [hunk 1]
```diff
@@ -1,4 +1,4 @@
-const object = require('lodash/fp/object');
+const getObject = require('lodash/get');
```
Comment (AkalUstat) [inline api/lib/getJSON.js:1]: just fyi @ManjotS looks like `fp/object` lib has been deprecated -> its not available in the main master branch of lodash anymore

Comment (AkalUstat) [reply api/lib/getJSON.js:1]: never mind i spoke too soon, it exists under this branch `https://github.com/lodash/lodash/tree/4.17.15-post/fp` which is the same version we're using

Comment (AkalUstat) [reply api/lib/getJSON.js:1]: point still stands that the `object.js` file no long exists
